language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"

sudo: enabled

# Command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls

# Add databases.
services:
  - postgresql
  - redis-server

# Environment variables.
env:
  - DATABASE_URL=postgres:///$(whoami) REDIS_URL=redis://

# Build for master branch only.
branches:
  only:
    - master

# Command to run tests
script: coverage run --source=movie_scheduler,scheduler_core manage.py test -v 2

after_success: coveralls