# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieschedule',
            name='ratings',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
