# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_core', '0002_auto_20170321_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latestupdate',
            name='latest_update',
            field=models.DateTimeField(null=True),
        ),
    ]
